# Generated by Django 3.1.14 on 2022-06-25 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grabacion',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_trabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon', to='backend.salones'),
        ),
        migrations.CreateModel(
            name='padres',
            fields=[
                ('id_padre', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_padre', models.CharField(max_length=255)),
                ('apellido_padre', models.CharField(max_length=250)),
                ('fechaInscripcion', models.CharField(max_length=250)),
                ('fechanacimiento', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('celular', models.IntegerField(default=0)),
                ('telefonoCasa', models.IntegerField(default=0)),
                ('telefonoOficina', models.IntegerField(default=0)),
                ('huella', models.CharField(max_length=250)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rol', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
